import type { Merchant } from './types'

// Hand-authored, not randomly generated, so specific edge cases (brand-new
// merchant, high-value account going quiet, missing CSAT, recently-contacted
// merchant) are guaranteed to be present and checkable, rather than left to
// chance.
export const seedMerchants: Merchant[] = [
  {
    id: 'm-001',
    name: 'Riverside Coffee Co.',
    planTier: 'growth',
    mrr: 420,
    tenureDays: 540,
    daysSinceLastTransaction: 52,
    txnVolumeTrend30d: -38,
    paymentFailureRate30d: 0.02,
    openSupportTickets: 0,
    csatScore: 3,
    lastContactDaysAgo: 21,
  },
  {
    id: 'm-002',
    name: 'Northbridge Hardware',
    planTier: 'enterprise',
    mrr: 3200,
    tenureDays: 900,
    daysSinceLastTransaction: 3,
    txnVolumeTrend30d: -22,
    paymentFailureRate30d: 0.01,
    openSupportTickets: 1,
    csatScore: 4,
    lastContactDaysAgo: 40,
  },
  {
    id: 'm-003',
    name: 'Pixel & Pine Studio',
    planTier: 'starter',
    mrr: 60,
    tenureDays: 8,
    daysSinceLastTransaction: 8,
    txnVolumeTrend30d: 0,
    paymentFailureRate30d: 0,
    openSupportTickets: 0,
    csatScore: null,
    lastContactDaysAgo: 2,
  },
  {
    id: 'm-004',
    name: 'Summit Fitness Gear',
    planTier: 'growth',
    mrr: 890,
    tenureDays: 365,
    daysSinceLastTransaction: 1,
    txnVolumeTrend30d: 12,
    paymentFailureRate30d: 0.35,
    openSupportTickets: 2,
    csatScore: 3,
    lastContactDaysAgo: 15,
  },
  {
    id: 'm-005',
    name: 'Marlowe & Finch Books',
    planTier: 'starter',
    mrr: 45,
    tenureDays: 210,
    daysSinceLastTransaction: 4,
    txnVolumeTrend30d: 6,
    paymentFailureRate30d: 0,
    openSupportTickets: 0,
    csatScore: 5,
    lastContactDaysAgo: 60,
  },
  {
    id: 'm-006',
    name: 'Cascade Outdoor Supply',
    planTier: 'enterprise',
    mrr: 5100,
    tenureDays: 1200,
    daysSinceLastTransaction: 45,
    txnVolumeTrend30d: -55,
    paymentFailureRate30d: 0.08,
    openSupportTickets: 4,
    csatScore: 2,
    lastContactDaysAgo: 30,
  },
  {
    id: 'm-007',
    name: 'Little Sprout Nursery',
    planTier: 'starter',
    mrr: 30,
    tenureDays: 3,
    daysSinceLastTransaction: 3,
    txnVolumeTrend30d: 0,
    paymentFailureRate30d: 0,
    openSupportTickets: 0,
    csatScore: null,
    lastContactDaysAgo: 1,
  },
  {
    id: 'm-008',
    name: 'Anchor Point Electronics',
    planTier: 'growth',
    mrr: 1500,
    tenureDays: 680,
    daysSinceLastTransaction: 2,
    txnVolumeTrend30d: -5,
    paymentFailureRate30d: 0.01,
    openSupportTickets: 6,
    csatScore: 2,
    lastContactDaysAgo: 90,
  },
  {
    id: 'm-009',
    name: 'Golden Hour Photography',
    planTier: 'starter',
    mrr: 25,
    tenureDays: 400,
    daysSinceLastTransaction: 70,
    txnVolumeTrend30d: -80,
    paymentFailureRate30d: 0.5,
    openSupportTickets: 3,
    csatScore: 1,
    lastContactDaysAgo: 120,
  },
  {
    id: 'm-010',
    name: 'Willow Creek Bakery',
    planTier: 'growth',
    mrr: 610,
    tenureDays: 300,
    daysSinceLastTransaction: 0,
    txnVolumeTrend30d: 15,
    paymentFailureRate30d: 0,
    openSupportTickets: 0,
    csatScore: 5,
    lastContactDaysAgo: 10,
  },
]
